### ISSUE TITLE
ToDo app API error AttributeError: module 'sqlalchemy.util' has no attribute 'py2k'

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/dapp-experiments#6]
I am trying to run the docker-compose example of the ToDo app. First issue I noticed was that it requires the docker images to be built on an amd64 architecture, because if the container is of aarch64 architecture, then you will receive an error about an expecting lib file named something with `/..../....x86-64 ....` . I solved this by adding line `platform: linux/amd64` to all of the images in the docker-compose file. 

Fast forward, everything builds as expected and runs, but the last issue remaining is that the API will exit unexpectedly on container start due to the following error:

`AttributeError: module 'sqlalchemy.util' has no attribute 'py2k'`

I saw that the `requirements.txt` file has fixed versions of the libraries, so I would assume everything has been confirmed to run as expected before pushing to the repository. Regardless of that I tried to check if for example `sqlalchemy_rqlite` had a newer version, but it was using the latest. Secondly I checked `flask-sqlalchemy` for new versions and there was just a patch release namely from `3.0.0` to `3.0.3` - but that doesn't fix it either.

This is the traceback from the container log

```
Traceback (most recent call last):
  File "/webapp/app.py", line 21, in <module>
    db = SQLAlchemy(app)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 219, in __init__
    self.init_app(app)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 320, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 606, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 556, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 754, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 363, in load
    return impl.load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_rqlite/pyrqlite.py", line 39, in <module>
    class SQLiteDialect_rqlite(SQLiteDialect):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_rqlite/pyrqlite.py", line 50, in SQLiteDialect_rqlite
    if not util.py2k:
AttributeError: module 'sqlalchemy.util' has no attribute 'py2k'
Traceback (most recent call last):
  File "/webapp/app.py", line 21, in <module>
    db = SQLAlchemy(app)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 219, in __init__
    self.init_app(app)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 320, in init_app
    engines[key] = self._make_engine(key, options, app)
  File "/usr/local/lib/python3.9/site-packages/flask_sqlalchemy/extension.py", line 606, in _make_engine
    return sa.engine_from_config(options, prefix="")
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 817, in engine_from_config
    return create_engine(url, **options)
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 277, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 556, in create_engine
    entrypoint = u._get_entrypoint()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 754, in _get_entrypoint
    cls = registry.load(name)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 363, in load
    return impl.load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_rqlite/pyrqlite.py", line 39, in <module>
    class SQLiteDialect_rqlite(SQLiteDialect):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy_rqlite/pyrqlite.py", line 50, in SQLiteDialect_rqlite
    if not util.py2k:
AttributeError: module 'sqlalchemy.util' has no attribute 'py2k'
```

### Info about my system
M1 Macbook (ARM64 system) 
Docker Desktop ARM64 for Mac version 4.12.0

**Comment by VanDavv** [comment]
Goal of this task is to:
- [ ] Build and run the ToDo app experiment on Linux and verify if it works
- [ ] Build and run the ToDo app on Mac M1 to recreate the issue (I do have one on my side)
- [ ] Resolve or mitigate the issue:
  - Verify what are the possible differences in Linux and Mac builds, e.g. different versions, or using source builds (`.tar.gz` or `.zip`) instead of binary builds (`.whl`)
  - Try to resolve the issue by either updating/downgrading the library version numbers or making adjustments to the build process (e.g. `platform` key for docker-compose) 
  - If there's no possible solution or workaround, we should at least provide a mention about a local development being bugged on Mac M1 inside of our README.md and create an open issue with the things we tried in order to resolve it

**Comment by cryptobench** [comment]
One important thing to note is that running the API locally **without** docker on the M1 macbook works perfectly fine. I just noticed it during test of the whole stack with docker-compose.

**Comment by grisha87** [comment]
Hey SDK team. Upon request of @shadeofblue I came back to @cryptobench to determine the importance and urgency of the issue. It turns out that it's neither important nor urgent from the perspective of the Showcase Team day-to-day operation.

Please consider this as a "finding" which might affect some users which would like to start the dapps using docker-compose on Macs and deal with this as it would be reported by anyone from the community. I'm not able to help you with prioritization of such case, as that's something internal for your team :)
